In [1]:
import pandas as pd

In [2]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

In [3]:
myvar

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [8]:
pd.Series(mydataset)

cars        [BMW, Volvo, Ford]
passings             [3, 7, 2]
dtype: object

In [5]:
a = [1, 7, 2]

mycol = pd.Series(a, index = ['a','b','c'])
mycol

a    1
b    7
c    2
dtype: int64

In [7]:
mycol['a']

np.int64(1)

In [11]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [15]:
x=df.loc[0]
x

calories    420
duration     50
Name: 0, dtype: int64

In [16]:
y=df.loc[[0]]
y

   calories  duration
0       420        50

In [17]:
type(x)

pandas.core.series.Series

In [18]:
type(y)

pandas.core.frame.DataFrame

In [20]:
df.loc[[0,1]]

   calories  duration
0       420        50
1       380        40

In [21]:
import pandas as pd

# 1️⃣ 创建原始长格式 DataFrame
data = {
    'City': ['NY', 'NY', 'SF', 'SF', 'LA', 'LA'],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [10, 20, 30, 40, 50, 60]
}

df = pd.DataFrame(data)
print("原始长格式 DataFrame:")
print(df)

原始长格式 DataFrame:
  City Product  Sales
0   NY       A     10
1   NY       B     20
2   SF       A     30
3   SF       B     40
4   LA       A     50
5   LA       B     60

In [ ]:
df1 = df.groupby(['City','Product'])['Sales'].sum()
df1 #聚合结果（长格式 + MultiIndex)

City  Product
LA    A          50
      B          60
NY    A          10
      B          20
SF    A          30
      B          40
Name: Sales, dtype: int64

In [26]:
df2 = df1.unstack() #宽格式
df2

Product   A   B
City
LA       50  60
NY       10  20
SF       30  40

In [27]:
df2['A']+df2['B']

City
LA    110
NY     30
SF     70
dtype: int64

In [28]:
df

  City Product  Sales
0   NY       A     10
1   NY       B     20
2   SF       A     30
3   SF       B     40
4   LA       A     50
5   LA       B     60

In [33]:
df.pivot_table(index = 'City', columns = 'Product', values = 'Sales', aggfunc = sum)

/var/folders/kt/p5tb82rx45sc95qpd5lyj1bm0000gn/T/ipykernel_4349/2841518187.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index = 'City', columns = 'Product', values = 'Sales', aggfunc = sum)

Product   A   B
City
LA       50  60
NY       10  20
SF       30  40